const strategies = {
  bull: [
    {
      name: "Long Call",
      image: "long-call.png",
      template: [
        {
          type: "call",
          action: "buy",
          strick_price: 0,
          premium: 0.0,
          lot: 1,
          help: "",
        },
      ],
    },
    {
      name: "Short Put",
      image: "short-put.png",
      template: [
        {
          type: "put",
          action: "sell",
          strick_price: 0,
          premium: 0.0,
          lot: 1,
          help: "",
        },
      ],
    },
    {
      name: "Bull Call Spread",
      image: "bull-call-spread.png",
      template: [
        {
          type: "call",
          action: "buy",
          strick_price: 0,
          premium: 0.0,
          lot: 1,
          help: "Buy At the money call.",
        },
        {
          type: "call",
          action: "sell",
          strick_price: 0,
          premium: 0.0,
          lot: 1,
          help: "Sell out the money call.",
        },
      ],
    },
    {
      name: "Bull Put Spread",
      image: "bull-put-spread.png",
      template: [
        {
          type: "put",
          action: "buy",
          strick_price: 0,
          premium: 0.0,
          lot: 1,
          help: "Buy In the money put.",
        },
        {
          type: "put",
          action: "sell",
          strick_price: 0,
          premium: 0.0,
          lot: 1,
          help: "Sell At the money put.",
        },
      ],
    },
    // {
    //   name: "Call Ratio Back Spread",
    //   image: "call-ratio-back-spread.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 2,
    //       help: "Sell At the money call.",
    //     },
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy 2 Out the money call.",
    //     },
    //   ],
    // },
    // {
    //   name: "Long Synthetic",
    //   image: "long-synthetic.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy At the money call.",
    //     },
    //     {
    //       type: "put",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell At the money put.",
    //     },
    //   ],
    // },
    // {
    //   name: "Range Forward",
    //   image: "range-forward.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell In the money call.",
    //     },
    //     {
    //       type: "put",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell Out the money put.",
    //     },
    //   ],
    // },
    // {
    //   name: "Bullish Butterfly",
    //   image: "bullish-butterfly.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Lower strike call.",
    //     },
    //     {
    //       type: "call",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 2,
    //       help: "Sell Middle strike call.",
    //     },
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Higher strike call.",
    //     },
    //   ],
    // },
    // {
    //   name: "Bullish Condor",
    //   image: "bullish-condor.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Out the money call.",
    //     },
    //     {
    //       type: "call",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell At the money call.",
    //     },
    //     {
    //       type: "put",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell At the money put.",
    //     },
    //     {
    //       type: "put",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Out the money put.",
    //     },
    //   ],
    // },
  ],
  bear: [
    {
      name: "Short Call",
      image: "short-call.png",
      template: [
        {
          type: "call",
          action: "sell",
          strick_price: 0,
          premium: 0.0,
          lot: 1,
          help: "",
        },
      ],
    },
    {
      name: "Long Put",
      image: "long-put.png",
      template: [
        {
          type: "put",
          action: "buy",
          strick_price: 0,
          premium: 0.0,
          lot: 1,
          help: "",
        },
      ],
    },
    {
      name: "Bear Call Spread",
      image: "bear-call-spread.png",
      template: [
        {
          type: "call",
          action: "sell",
          strick_price: 0,
          premium: 0.0,
          lot: 1,
          help: "Sell At the money call.",
        },
        {
          type: "call",
          action: "buy",
          strick_price: 0,
          premium: 0.0,
          lot: 1,
          help: "Buy out the money call.",
        },
      ],
    },
    {
      name: "Bear Put Spread",
      image: "bear-put-spread.png",
      template: [
        {
          type: "put",
          action: "buy",
          strick_price: 0,
          premium: 0.0,
          lot: 1,
          help: "Buy In the money put.",
        },
        {
          type: "put",
          action: "sell",
          strick_price: 0,
          premium: 0.0,
          lot: 1,
          help: "Sell At the money put.",
        },
      ],
    },
    // {
    //   name: "Put Ratio Back Spread",
    //   image: "put-ratio-back-spread.png",
    //   template: [
    //     {
    //       type: "put",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy 2 In the money put.",
    //     },
    //     {
    //       type: "put",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell 3 Out the money put.",
    //     },
    //   ],
    // },
    // {
    //   name: "Short Synthetic",
    //   image: "short-synthetic.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell At the money call.",
    //     },
    //     {
    //       type: "put",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy At the money put.",
    //     },
    //   ],
    // },
    // {
    //   name: "Risk Reversal",
    //   image: "risk-reversal.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy At the money call.",
    //     },
    //     {
    //       type: "put",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell At the money put.",
    //     },
    //   ],
    // },
    // {
    //   name: "Bearish Butterfly",
    //   image: "bearish-butterfly.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Out the money call.",
    //     },
    //     {
    //       type: "call",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell At the money call.",
    //     },
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy In the money call.",
    //     },
    //   ],
    // },
    // {
    //   name: "Bearish Condor",
    //   image: "bearish-condor.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Out the money call.",
    //     },
    //     {
    //       type: "call",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell At the money call.",
    //     },
    //     {
    //       type: "put",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell At the money put.",
    //     },
    //     {
    //       type: "put",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Out the money put.",
    //     },
    //   ],
    // },
  ],
  non_dir: [
    {
      name: "Long Straddle",
      image: "long-straddle.png",
      template: [
        {
          type: "call",
          action: "buy",
          strick_price: 0,
          premium: 0.0,
          lot: 1,
          help: "Buy At the money call.",
        },
        {
          type: "put",
          action: "buy",
          strick_price: 0,
          premium: 0.0,
          lot: 1,
          help: "Buy At the money put.",
        },
      ],
    },
    {
      name: "Short Straddle",
      image: "short-straddle.png",
      template: [
        {
          type: "call",
          action: "sell",
          strick_price: 0,
          premium: 0.0,
          lot: 1,
          help: "Sell At the money call.",
        },
        {
          type: "put",
          action: "sell",
          strick_price: 0,
          premium: 0.0,
          lot: 1,
          help: "Sell At the money put.",
        },
      ],
    },
    {
      name: "Long Strangle",
      image: "long-strangle.png",
      template: [
        {
          type: "call",
          action: "buy",
          strick_price: 0,
          premium: 0.0,
          lot: 1,
          help: "Buy Out the money call.",
        },
        {
          type: "put",
          action: "buy",
          strick_price: 0,
          premium: 0.0,
          lot: 1,
          help: "Buy Out the money put.",
        },
      ],
    },
    {
      name: "Short Strangle",
      image: "short-strangle.png",
      template: [
        {
          type: "call",
          action: "sell",
          strick_price: 0,
          premium: 0.0,
          lot: 1,
          help: "Sell Out the money call.",
        },
        {
          type: "put",
          action: "sell",
          strick_price: 0,
          premium: 0.0,
          lot: 1,
          help: "Sell Out the money put.",
        },
      ],
    },
    // {
    //   name: "Jade Lizard Reverse",
    //   image: "jade-lizard-reverse.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell Out the money call.",
    //     },
    //     {
    //       type: "put",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell Out the money put.",
    //     },
    //     {
    //       type: "put",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Out the money put.",
    //     },
    //   ],
    // },
    // {
    //   name: "Jade Lizard",
    //   image: "jade-lizard.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell Out the money call.",
    //     },
    //     {
    //       type: "put",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell Out the money put.",
    //     },
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Out the money call.",
    //     },
    //   ],
    // },
    // {
    //   name: "Call Ratio Spread",
    //   image: "call-ratio-spread.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell At the money call.",
    //     },
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy 2 Out the money call.",
    //     },
    //   ],
    // },
    // {
    //   name: "Put Ratio Spread",
    //   image: "put-ratio-spread.png",
    //   template: [
    //     {
    //       type: "put",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell At the money put.",
    //     },
    //     {
    //       type: "put",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy 2 Out the money put.",
    //     },
    //   ],
    // },
    // {
    //   name: "Batman Strategy",
    //   image: "batman-strategy.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Out the money call.",
    //     },
    //     {
    //       type: "call",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell At the money call.",
    //     },
    //     {
    //       type: "put",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Out the money put.",
    //     },
    //     {
    //       type: "put",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell At the money put.",
    //     },
    //   ],
    // },
    // {
    //   name: "Long Iron Fly",
    //   image: "long-iron-fly.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Out the money call.",
    //     },
    //     {
    //       type: "call",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell At the money call.",
    //     },
    //     {
    //       type: "put",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Out the money put.",
    //     },
    //     {
    //       type: "put",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell At the money put.",
    //     },
    //   ],
    // },
    // {
    //   name: "Short Iron Fly",
    //   image: "short-iron-fly.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell Out the money call.",
    //     },
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy At the money call.",
    //     },
    //     {
    //       type: "put",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell Out the money put.",
    //     },
    //     {
    //       type: "put",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy At the money put.",
    //     },
    //   ],
    // },
    // {
    //   name: "Double Fly",
    //   image: "double-fly.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell Out the money call.",
    //     },
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy At the money call.",
    //     },
    //     {
    //       type: "put",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell Out the money put.",
    //     },
    //     {
    //       type: "put",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy At the money put.",
    //     },
    //   ],
    // },
    // {
    //   name: "Long Iron Condor",
    //   image: "long-iron-condor.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Out the money call.",
    //     },
    //     {
    //       type: "call",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell At the money call.",
    //     },
    //     {
    //       type: "put",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell At the money put.",
    //     },
    //     {
    //       type: "put",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Out the money put.",
    //     },
    //   ],
    // },
    // {
    //   name: "Short Iron Condor",
    //   image: "short-iron-condor.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell Out the money call.",
    //     },
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy At the money call.",
    //     },
    //     {
    //       type: "put",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell Out the money put.",
    //     },
    //     {
    //       type: "put",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy At the money put.",
    //     },
    //   ],
    // },
    // {
    //   name: "Double Condor",
    //   image: "double-condor.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell Out the money call.",
    //     },
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy At the money call.",
    //     },
    //     {
    //       type: "put",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell Out the money put.",
    //     },
    //     {
    //       type: "put",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy At the money put.",
    //     },
    //   ],
    // },
    // {
    //   name: "Call Calendar",
    //   image: "call-calendar.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell Near-term call.",
    //     },
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Far-term call.",
    //     },
    //   ],
    // },
    // {
    //   name: "Put Calendar",
    //   image: "put-calendar.png",
    //   template: [
    //     {
    //       type: "put",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell Near-term put.",
    //     },
    //     {
    //       type: "put",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Far-term put.",
    //     },
    //   ],
    // },
    // {
    //   name: "Diagonal Calendar",
    //   image: "diagonal-calendar.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell Near-term call.",
    //     },
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Far-term call.",
    //     },
    //     {
    //       type: "put",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Sell Near-term put.",
    //     },
    //     {
    //       type: "put",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Far-term put.",
    //     },
    //   ],
    // },
    // {
    //   name: "Call Butterfly",
    //   image: "call-butterfly.png",
    //   template: [
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Lower strike call.",
    //     },
    //     {
    //       type: "call",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 2,
    //       help: "Sell Middle strike call.",
    //     },
    //     {
    //       type: "call",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Higher strike call.",
    //     },
    //   ],
    // },
    // {
    //   name: "Put Butterfly",
    //   image: "put-butterfly.png",
    //   template: [
    //     {
    //       type: "put",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Lower strike put.",
    //     },
    //     {
    //       type: "put",
    //       action: "sell",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 2,
    //       help: "Sell Middle strike put.",
    //     },
    //     {
    //       type: "put",
    //       action: "buy",
    //       strick_price: 0,
    //       premium: 0.0,
    //       lot: 1,
    //       help: "Buy Higher strike put.",
    //     },
    //   ],
    // },
  ],
};

export default strategies;
