# Generated by Django 5.0.4 on 2024-04-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fii_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='fii_data',
            name='date',
            field=models.DateField(default='2018-04-01'),
        ),
    ]
